# functions to write gadget files

#' Write Gadget mainfile to a text file
#'
#' Writes a Gadget main file from an R list containing class gadget.main to a
#' text file to be used by Gadget
#'
#' @param obj A list also containing class \code{gadget.main}
#' @param file Name of the file to write to
#'
#' @return NULL
#' @export
#'
#' @examples
#' write_gadget_main(gadget_main_default)
#' write_gadget_main()
write_gadget_main <- function(obj = NULL, file = "main") {
    if (is.null(obj)) {
        obj <- gadget_main_default
        warning(paste("No Gadget main file found. Writing the default to file",
                file))
    } else if (!("gadget.main" %in% class(obj))) {
        stop("Class of file should contain gadget.main.")
    }
    if (length(obj$printfiles) == 0) {
        obj$printfiles <- "; Required comment"
    }
    filenames <-
        vapply(obj, function(x) {
            return(paste0("\t", x, collapse = "\t"))
        }, character(1))
    mainfile <- paste0(names(filenames), filenames)
    tap_names <- c("timefile", "areafile", "printfiles")
    match_main <- match(tap_names, names(obj))
    if (any(is.na(match_main))) {
        stop("One of timefile, areafile, or printfiles missing.")
    }
    tap_files <- mainfile[match_main]
    keywords <-
        list(stock = "stockfiles",
             tagging = "tagfiles",
             otherfood = "otherfoodfiles",
             fleet = "fleetfiles",
             likelihood = "likelihoodfiles")
    matchkey <- match(names(filenames), keywords, nomatch = 0)
    keywords[matchkey] <- mainfile[4:length(mainfile)]
    main_template <-
        c(sprintf("; Generated by gadgetSim %s", packageVersion("gadgetSim")),
          tap_files,
          keywords)
    main <-
        lapply(seq_along(main_template), function(x, n) {
            if (n[x] == "") {
                return(c(main_template[[x]]))
            } else {
                return(c(paste0("[", n[x], "]"),
                         main_template[[x]]))
            }
        }, n = names(main_template))
    main <- unlist(main)
    write(main, file = file, sep = "\n")
}


write_printfile <- function(file, printatstart = 1, steps = "all") {

}


